In [22]:
import numpy as np
arr = np.array([[1,2,3,4.5]])
arr.dtype

dtype('float64')

In [18]:
arr.argmin()

0

In [23]:
arr

array([[1. , 2. , 3. , 4.5]])

In [10]:
arr.sum()

10.5

In [11]:
arr.cumsum()

array([ 1. ,  3. ,  6. , 10.5])

# 2019-12-10

## boolean Methods

In [20]:
arr[0][0] = 0
arr

array([[0. , 2. , 3. , 4.5]])

In [25]:
print(arr)
arr.all()

[[1.  2.  3.  4.5]]


True

In [56]:
arr2 = np.array((23,5,76,87,78,2,12,45)).reshape(2,4)
arr2

array([[23,  5, 76, 87],
       [78,  2, 12, 45]])

In [57]:
arr2.sort(1)

In [58]:
arr2

array([[ 5, 23, 76, 87],
       [ 2, 12, 45, 78]])

In [60]:
arr3 = np.array((23,5,76,87,78,2,12,45)).reshape(2,4)
arr3.sort(0)
arr3

array([[23,  2, 12, 45],
       [78,  5, 76, 87]])

In [61]:
np.save("test_array",arr2)

In [62]:
np.load('test_array.npy')

array([[ 5, 23, 76, 87],
       [ 2, 12, 45, 78]])

In [63]:
a = np.arange(10)
b = np.arange(10)*2

In [80]:
np.savez('test_zip',x = a,y = b)

In [81]:
t = np.load('test_zip.npz')

In [82]:
t['x']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [89]:
arr2

array([[ 5, 23, 76, 87],
       [ 2, 12, 45, 78]])

In [93]:
np.transpose(arr2)

array([[ 5,  2],
       [23, 12],
       [76, 45],
       [87, 78]])

In [94]:
arr2.T

array([[ 5,  2],
       [23, 12],
       [76, 45],
       [87, 78]])

In [97]:
m = np.dot(arr2,arr2.T)
m

array([[13899, 10492],
       [10492,  8257]])

In [98]:
np.linalg.det(m)

4681979.0

In [99]:
np.linalg.inv(m)

array([[ 0.00176357, -0.00224093],
       [-0.00224093,  0.00296862]])

### Array Manipulation

In [100]:
arr2

array([[ 5, 23, 76, 87],
       [ 2, 12, 45, 78]])

In [101]:
arr3

array([[23,  2, 12, 45],
       [78,  5, 76, 87]])

In [105]:
np.concatenate([arr2, arr3])

array([[ 5, 23, 76, 87],
       [ 2, 12, 45, 78],
       [23,  2, 12, 45],
       [78,  5, 76, 87]])

In [106]:
np.concatenate([arr2, arr3],axis = 1) 

array([[ 5, 23, 76, 87, 23,  2, 12, 45],
       [ 2, 12, 45, 78, 78,  5, 76, 87]])

In [107]:
np.concatenate([arr2, arr3],axis = 0) 

array([[ 5, 23, 76, 87],
       [ 2, 12, 45, 78],
       [23,  2, 12, 45],
       [78,  5, 76, 87]])

In [112]:
# vstack
np.vstack([arr2,arr3])

array([[ 5, 23, 76, 87],
       [ 2, 12, 45, 78],
       [23,  2, 12, 45],
       [78,  5, 76, 87]])

In [113]:
np.hstack([arr2,arr3])

array([[ 5, 23, 76, 87, 23,  2, 12, 45],
       [ 2, 12, 45, 78, 78,  5, 76, 87]])

In [118]:
# Split
arr2.resize(1,8)
arr2

array([[ 5, 23, 76, 87,  2, 12, 45, 78]])

In [166]:
x ,y ,z = np.split(arr3,[2,1])

In [167]:
x

array([[23,  2, 12, 45],
       [78,  5, 76, 87]])

In [168]:
y

array([], shape=(0, 4), dtype=int32)

In [160]:
z

array([[78,  5, 76, 87]])

In [149]:
p = np.arange(16)
np.split(p,[2,8])

[array([0, 1]),
 array([2, 3, 4, 5, 6, 7]),
 array([ 8,  9, 10, 11, 12, 13, 14, 15])]

In [165]:
np.split(arr3,indices_or_sections=[1,2])

[array([[23,  2, 12, 45]]),
 array([[78,  5, 76, 87]]),
 array([], shape=(0, 4), dtype=int32)]

### Stacking helpers: r_ and c_ 

In [176]:
np.c_[1:16]

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15]])

In [177]:
np.r_[1:16]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

### Repeating Elements: tile and repeat 

In [180]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [183]:
a.repeat([2])

array([0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9])

In [220]:
arr3

array([[23,  2, 12, 45],
       [78,  5, 76, 87]])

In [232]:
arr3.repeat(2,axis =1)


array([[23, 23,  2,  2, 12, 12, 45, 45],
       [78, 78,  5,  5, 76, 76, 87, 87]])

In [239]:
s = np.arange(16).reshape(2,2,4)
s

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [241]:
s.repeat([2,3],axis = 1)

array([[[ 0,  1,  2,  3],
        [ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 4,  5,  6,  7],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [12, 13, 14, 15],
        [12, 13, 14, 15]]])

In [237]:
np.repeat(3,4)

array([3, 3, 3, 3])

In [243]:
np.tile(s,(2,3))

array([[[ 0,  1,  2,  3,  0,  1,  2,  3,  0,  1,  2,  3],
        [ 4,  5,  6,  7,  4,  5,  6,  7,  4,  5,  6,  7],
        [ 0,  1,  2,  3,  0,  1,  2,  3,  0,  1,  2,  3],
        [ 4,  5,  6,  7,  4,  5,  6,  7,  4,  5,  6,  7]],

       [[ 8,  9, 10, 11,  8,  9, 10, 11,  8,  9, 10, 11],
        [12, 13, 14, 15, 12, 13, 14, 15, 12, 13, 14, 15],
        [ 8,  9, 10, 11,  8,  9, 10, 11,  8,  9, 10, 11],
        [12, 13, 14, 15, 12, 13, 14, 15, 12, 13, 14, 15]]])

###  Pandas

In [250]:
import pandas as pd
di = {'name': ["ravi",'balu','G1'],'number': [1,2,3],'age': [19,18,np.nan]}
di

{'name': ['ravi', 'balu', 'G1'], 'number': [1, 2, 3], 'age': [19, 18, nan]}

In [254]:
df = pd.DataFrame(di, index = ['p1','p2','p3'])

In [255]:
df['name']

p1    ravi
p2    balu
p3      G1
Name: name, dtype: object

In [256]:
di2 = {'name': 'ravi','number': 1,'age': 19}
di2

{'name': 'ravi', 'number': 1, 'age': 19}

In [257]:
pd.Series(di2)

name      ravi
number       1
age         19
dtype: object

In [260]:
ds1 = pd.Series([10,20,30])
ds1

0    10
1    20
2    30
dtype: int64

In [262]:
ds1.values

array([10, 20, 30], dtype=int64)

In [265]:
df.values

array([['ravi', 1, 19.0],
       ['balu', 2, 18.0],
       ['G1', 3, nan]], dtype=object)

In [266]:
df.index

Index(['p1', 'p2', 'p3'], dtype='object')