In [1]:
import numpy as np


In [3]:
a = np.array([1,2,3,4])

In [8]:
a.shape

(4,)

In [13]:
a1 = np.array([[1,2,3],[2,3,4]])
a1

array([[1, 2, 3],
       [2, 3, 4]])

In [14]:
a1.shape

(2, 3)

In [21]:
a2 = np.array([[1,2,3],[4,5,6],[12,13,14],[24,76,2]])

In [22]:
a2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [12, 13, 14],
       [24, 76,  2]])

In [23]:
a2.shape

(4, 3)

In [67]:
help(np.random.randn)

Help on built-in function randn:

randn(...) method of mtrand.RandomState instance
    randn(d0, d1, ..., dn)
    
    Return a sample (or samples) from the "standard normal" distribution.
    
    If positive, int_like or int-convertible arguments are provided,
    `randn` generates an array of shape ``(d0, d1, ..., dn)``, filled
    with random floats sampled from a univariate "normal" (Gaussian)
    distribution of mean 0 and variance 1 (if any of the :math:`d_i` are
    floats, they are first converted to integers by truncation). A single
    float randomly sampled from the distribution is returned if no
    argument is provided.
    
    This is a convenience function.  If you want an interface that takes a
    tuple as the first argument, use `numpy.random.standard_normal` instead.
    
    Parameters
    ----------
    d0, d1, ..., dn : int, optional
        The dimensions of the returned array, should be all positive.
        If no argument is given a single Python float is ret

In [28]:
a3 = np.random.randn(2,4,2)
a3

array([[[-0.18332622,  1.13570178],
        [ 0.54736581,  0.72105952],
        [ 1.78424022,  0.25581056],
        [ 0.12901983,  0.58576545]],

       [[-0.22023429, -0.42506761],
        [ 0.38544087,  0.19816957],
        [ 1.41408086,  1.57641737],
        [ 0.33822105,  0.42029643]]])

In [29]:
a3.shape

(2, 4, 2)

# Arthritics on array  

In [32]:
a1

array([[1, 2, 3],
       [2, 3, 4]])

In [33]:
a1+a1

array([[2, 4, 6],
       [4, 6, 8]])

In [35]:
a1*a1

array([[ 1,  4,  9],
       [ 4,  9, 16]])

In [54]:
a3.dtype

dtype('float64')

In [55]:
a3[0][0][0] = 'test'

ValueError: could not convert string to float: 'test'

In [38]:
a3

array([[[100.        ,   1.13570178],
        [  0.54736581,   0.72105952],
        [  1.78424022,   0.25581056],
        [  0.12901983,   0.58576545]],

       [[ -0.22023429,  -0.42506761],
        [  0.38544087,   0.19816957],
        [  1.41408086,   1.57641737],
        [  0.33822105,   0.42029643]]])

In [47]:
a1.dtype

dtype('int32')

In [49]:
print(a2)
a2.dtype

[[ 1  2  3]
 [ 4  5  6]
 [12 13 14]
 [24 76  2]]


dtype('int32')

In [58]:
a2 = np.array([['abcd',2,3],[4,5,6],[12,13,14],[24,76,2]])

In [59]:
print(a2)
a2.dtype

[['abcd' '2' '3']
 ['4' '5' '6']
 ['12' '13' '14']
 ['24' '76' '2']]


dtype('<U4')

In [60]:
help(np.arange)

Help on built-in function arange in module numpy:

arange(...)
    arange([start,] stop[, step,], dtype=None)
    
    Return evenly spaced values within a given interval.
    
    Values are generated within the half-open interval ``[start, stop)``
    (in other words, the interval including `start` but excluding `stop`).
    For integer arguments the function is equivalent to the Python built-in
    `range` function, but returns an ndarray rather than a list.
    
    When using a non-integer step, such as 0.1, the results will often not
    be consistent.  It is better to use `numpy.linspace` for these cases.
    
    Parameters
    ----------
    start : number, optional
        Start of interval.  The interval includes this value.  The default
        start value is 0.
    stop : number
        End of interval.  The interval does not include this value, except
        in some cases where `step` is not an integer and floating point
        round-off affects the length of `out`.
   

In [61]:
a4 = np.arange(2,10)

In [63]:
a4.reshape(2,4)

array([[2, 3, 4, 5],
       [6, 7, 8, 9]])

In [64]:
a4.reshape(2,2,2)

array([[[2, 3],
        [4, 5]],

       [[6, 7],
        [8, 9]]])

In [65]:
a4.reshape(2,5)

ValueError: cannot reshape array of size 8 into shape (2,5)

In [68]:
help(np.ones)

Help on function ones in module numpy:

ones(shape, dtype=None, order='C')
    Return a new array of given shape and type, filled with ones.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: C
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    
    Returns
    -------
    out : ndarray
        Array of ones with the given shape, dtype, and order.
    
    See Also
    --------
    ones_like : Return an array of ones with shape and type of input.
    empty : Return a new uninitialized array.
    zeros : Return a new array setting values to zero.
    full : Return a new array of given shape filled with value.
    
    
    Examples
    --------
   

In [69]:
a1

array([[1, 2, 3],
       [2, 3, 4]])

In [71]:
a1[1][2] = 323

In [72]:
a1

array([[  1,   2,   3],
       [  2,   3, 323]])

In [97]:
a4.reshape(2,2,2)

array([[[2, 3],
        [4, 5]],

       [[6, 7],
        [8, 9]]])

In [98]:
a4

array([[2, 3, 4, 5],
       [6, 7, 8, 9]])

In [77]:
a4[1][0][1]

7

In [89]:
a4[1:,1:,1:]

array([[[9]]])

In [90]:
a4

array([[[2, 3],
        [4, 5]],

       [[6, 7],
        [8, 9]]])

In [91]:
a4.resize(2,4)

In [92]:
a4

array([[2, 3, 4, 5],
       [6, 7, 8, 9]])

# Boolean Indexing


In [101]:
a4

array([[2, 3, 4, 5],
       [6, 7, 8, 9]])

In [102]:
a4 < 5

array([[ True,  True,  True, False],
       [False, False, False, False]])

In [103]:
a4[a4 < 5]

array([2, 3, 4])

In [104]:
s_names = np.array(('raviteja','G1','ram','arun','vinod','satya','chaitanya'))

In [106]:
s_names

array(['raviteja', 'G1', 'ram', 'arun', 'vinod', 'satya', 'chaitanya'],
      dtype='<U9')

In [110]:
s_marks = np.array((35,32,1,91,26,76))

In [111]:
s_marks >= 35

array([ True, False, False,  True, False,  True])

In [112]:
s_names[s_marks >= 35]

IndexError: boolean index did not match indexed array along dimension 0; dimension is 7 but corresponding boolean dimension is 6

In [113]:
a4

array([[2, 3, 4, 5],
       [6, 7, 8, 9]])

In [115]:
a4[-1:,-2]

array([8])

In [116]:
a4.min()

2

In [127]:
np.argmin(a4,axis = 1)

array([0, 0], dtype=int64)

In [123]:
a4

array([[2, 3, 4, 5],
       [6, 7, 8, 9]])

In [125]:
a4.argmin()

0

In [126]:
a4[0]

array([2, 3, 4, 5])