# Pandas
## 11-12-2019

### Create a Data Series with Numpy array 

In [3]:
import pandas as pd 
import numpy as np
arr = np.array([2,3,5,6,np.nan])
arr

array([ 2.,  3.,  5.,  6., nan])

In [5]:
ds = pd.Series(arr)
ds

0    2.0
1    3.0
2    5.0
3    6.0
4    NaN
dtype: float64

In [6]:
n = list("ABCDEFGH")
ds1 = pd.Series(n)
ds1

0    A
1    B
2    C
3    D
4    E
5    F
6    G
7    H
dtype: object

### Create a Data Series with Dictionary

In [8]:
d = {'course':'Python',"college": "CRRCOE","Students": 20, 'fee': np.nan}
d

{'course': 'Python', 'college': 'CRRCOE', 'Students': 20, 'fee': nan}

In [12]:
pds = pd.Series(d)
pds

course      Python
college     CRRCOE
Students        20
fee            NaN
dtype: object

### Create a Data Frame  with Dictionary  and Numpy array

In [13]:
arr

array([ 2.,  3.,  5.,  6., nan])

In [14]:
n

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H']

In [15]:
d

{'course': 'Python', 'college': 'CRRCOE', 'Students': 20, 'fee': nan}

In [130]:
df1 = pd.DataFrame(arr)
df1

0
0  2.0
1  3.0
2  5.0
3  6.0
4  NaN

In [19]:
df2 = pd.DataFrame(n)
df2

0
0  A
1  B
2  C
3  D
4  E
5  F
6  G
7  H

In [25]:
d.keys()

dict_keys(['course', 'college', 'Students', 'fee'])

In [87]:
df3 = pd.DataFrame(d, index= d.keys())
df3

course college  Students  fee
course    Python  CRRCOE        20  NaN
college   Python  CRRCOE        20  NaN
Students  Python  CRRCOE        20  NaN
fee       Python  CRRCOE        20  NaN

In [88]:
df3.index = [1,2,3,4]
df3

course college  Students  fee
1  Python  CRRCOE        20  NaN
2  Python  CRRCOE        20  NaN
3  Python  CRRCOE        20  NaN
4  Python  CRRCOE        20  NaN

In [30]:
d2 = {"names": ['a','b','c'],'marks': [2,3,0],'rank':['A+','A','c']}
df4 = pd.DataFrame(d2)
df4

names  marks rank
0     a      2   A+
1     b      3    A
2     c      0    c

### Get values, index

In [38]:
ds

0    2.0
1    3.0
2    5.0
3    6.0
4    NaN
dtype: float64

In [36]:
ds.values

array([ 2.,  3.,  5.,  6., nan])

In [37]:
ds.index

RangeIndex(start=0, stop=5, step=1)

In [40]:
df4.index

RangeIndex(start=0, stop=3, step=1)

In [41]:
df4.values

array([['a', 2, 'A+'],
       ['b', 3, 'A'],
       ['c', 0, 'c']], dtype=object)

In [42]:
df4.columns

Index(['names', 'marks', 'rank'], dtype='object')

### Accesing Series data using indexing 

In [44]:
ds1[6]

'G'

In [45]:
df4

names  marks rank
0     a      2   A+
1     b      3    A
2     c      0    c

In [48]:
df4['names'][1]

'b'

### Using NumPy functions :    using masking, mathematics

In [52]:
ds[ds>3]

2    5.0
3    6.0
dtype: float64

In [58]:
df4[df4['marks'] >2]

names  marks rank
1     b      3    A

### isnull, pd.notnull

In [59]:
ds

0    2.0
1    3.0
2    5.0
3    6.0
4    NaN
dtype: float64

In [62]:
ds.isna()

0    False
1    False
2    False
3    False
4     True
dtype: bool

In [63]:
df1.isnull()

0
0  False
1  False
2  False
3  False
4   True

In [65]:
df4.notna()

names  marks  rank
0   True   True  True
1   True   True  True
2   True   True  True

### count of missing values

In [66]:
ds.isna().sum()

1

### DataFrame

In [69]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

### df.head(), df.sample()

In [71]:
data.head(3)

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11

In [73]:
data.tail(2)

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [75]:
data.sample(2)

one  two  three  four
Utah    8    9     10    11
Ohio    0    1      2     3

### Reindexing : 

In [77]:
df4

names  marks rank
0     a      2   A+
1     b      3    A
2     c      0    c

In [95]:
df4.reindex([1,2,3,4],fill_value= 0)

names  marks rank  test
1     0      0    0     0
2     0      0    0     0
3     0      0    0     0
4     0      0    0     0

In [86]:
df4.index = ['a','b','c']
df4

names  marks rank
a     a      2   A+
b     b      3    A
c     c      0    c

### adding a column in existing dataFrame

In [90]:
df4['test'] = [11,22,33]
df4

names  marks rank  test
a     a      2   A+    11
b     b      3    A    22
c     c      0    c    33

### Count non-NA cells for each column or row

nan

### Selection with loc and iloc

For DataFrame label-indexing on the rows,  the special **indexing operators loc and iloc  enable you to select a subset of the rows and columns from a DataFrame** .The difference between them is loc gets rows (or columns) with particular labels from the index,iloc gets rows (or columns)at particular positions in the index(though it takes only integers)


In [109]:
data=pd.DataFrame(np.arange(16).reshape((4, 4)),index=['Ohio', 'Colorado', 'Utah', 'New York'],  
                                                        columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [114]:
data.loc['Colorado',['one']]

one    4
Name: Colorado, dtype: int32

In [115]:
data.iloc[0]

one      0
two      1
three    2
four     3
Name: Ohio, dtype: int32

In [117]:
data.iloc[2,3]

11

### Arithmetic and Data Alignment 
An important pandas feature for some applications is the behavior of arithmetic between objects with different indexes. When you are adding together objects, if any index pairs are not the same, the respective index in the result will be the union of the index pairs. For users with database experience, this is similar to an automatic outer join on the index labels. 



In [118]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1],index=['a', 'c', 'e', 'f', 'g'])

In [119]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [120]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [121]:
s1+s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

###  Arithmetic methods with fill values
    using: df.add(fill_value = )

In [135]:
s1.add(s2, fill_value=0)

a    5.2
c    1.1
d    3.4
e    0.0
f    4.0
g    3.1
dtype: float64

### fillna

In [139]:
df1.fillna('missing')

0
0        2
1        3
2        5
3        6
4  missing

### deleting 
Ex: ds.drop(['d','c'])

In [140]:
df4

names  marks rank  test
a     a      2   A+    11
b     b      3    A    22
c     c      0    c    33

In [147]:
df = df4.drop('a')
df

names  marks rank  test
b     b      3    A    22
c     c      0    c    33

### is Identity operator

Ex: obj2.index is index 

In [148]:
df4

names  marks rank  test
a     a      2   A+    11
b     b      3    A    22
c     c      0    c    33

In [149]:
df

names  marks rank  test
b     b      3    A    22
c     c      0    c    33

In [150]:
df4.index

Index(['a', 'b', 'c'], dtype='object')

In [151]:
df.index

Index(['b', 'c'], dtype='object')

In [152]:
df.index is df4.index

False