In [5]:
import numpy as np

In [7]:
a = np.array([1,4,6])
a

array([1, 4, 6])

In [8]:
# mean 
np.mean(a)

3.6666666666666665

In [9]:
# min
np.min(a)

1

In [10]:
# max
np.max(a)

6

In [11]:
#std 
np.std(a)

2.0548046676563256

In [22]:
a

array([1, 4, 6])

In [25]:
((1-3.6)**2)+((4-3.6)**2)+((6-3.6)**2)

12.68

In [26]:
12.68/3

4.226666666666667

In [12]:
#var
np.var(a)

4.222222222222222

In [13]:
np.median(a)

4.0

In [15]:
np.mode(a)

AttributeError: module 'numpy' has no attribute 'mode'

In [16]:
from scipy import stats # for statistical calculations
a1 = np.array([[1,3,4,2,2,7],[5,2,2,1,4,1],[3,3,2,2,1,1]])

C:\ProgramData\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
C:\ProgramData\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [17]:
a1

array([[1, 3, 4, 2, 2, 7],
       [5, 2, 2, 1, 4, 1],
       [3, 3, 2, 2, 1, 1]])

In [20]:
m = stats.mode(a1) # most repeating values

In [21]:
m

ModeResult(mode=array([[1, 3, 2, 2, 1, 1]]), count=array([[1, 2, 2, 2, 1, 2]]))

In [27]:
rv = stats.poisson(2) #avg number of homes - 2

In [28]:
rv.pmf(3)  #we want to find out the likelihood that 3 homes will be sold tomorrow

0.18044704431548356

In [30]:
b = np.array([1,3,2])

In [32]:
np.mean(b)

2.0

In [33]:
np.median(b)

2.0

In [34]:
b = np.array([1,6,4])

In [35]:
np.mean(b)

3.6666666666666665

In [36]:
np.median(b)

4.0