# File Handling
    open
    read
    write
    append
    close
    tell
    seek
    method1

In [1]:
f = open("sample.txt","r") #open the file
data = f.read() # reading the data
print(data) # printing the data
f.close() # close the file

good morning CRRCOE


#### Second Method

In [3]:
with open("sample.txt","r") as f:
    data=f.read()
print(data)

good morning CRRCOE


In [4]:
def readdata(filename):
    f=open(filename,"r")
    data=f.read()
    print(data)
    f.close()

filename = input()

sample.txt


In [5]:
readdata(filename)

good morning CRRCOE


#### Write

In [6]:
with open("text.txt","w") as f:
    f.write(input())

python class


In [7]:
n=int(input())
for i in range(n):
    with open("text.txt","w") as f:
        f.write(input())

2
hi
hello


#### Append

In [10]:
n=int(input())
for i in range(n):
    with open("text.txt","a") as f:
        f.write('\n'+input())

2
12
34


In [11]:
dir(f)

['_CHUNK_SIZE',
 '__class__',
 '__del__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__enter__',
 '__eq__',
 '__exit__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__lt__',
 '__ne__',
 '__new__',
 '__next__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '_checkClosed',
 '_checkReadable',
 '_checkSeekable',
 '_checkWritable',
 '_finalizing',
 'buffer',
 'close',
 'closed',
 'detach',
 'encoding',
 'errors',
 'fileno',
 'flush',
 'isatty',
 'line_buffering',
 'mode',
 'name',
 'newlines',
 'read',
 'readable',
 'readline',
 'readlines',
 'reconfigure',
 'seek',
 'seekable',
 'tell',
 'truncate',
 'writable',
 'write',
 'write_through',
 'writelines']

In [13]:
help(f.readlines)

Help on built-in function readlines:

readlines(hint=-1, /) method of _io.TextIOWrapper instance
    Return a list of lines from the stream.
    
    hint can be specified to control the number of lines read: no more
    lines will be read if the total size (in bytes/characters) of all
    lines so far exceeds hint.



In [14]:
with open("text.txt") as f:
    data=f.readlines()
    for i in data:
        print(i)

helloabci

j



12

34


In [15]:
data

['helloabci\n', 'j\n', '\n', '12\n', '34']

In [20]:
print(len("".join(data)))
"".join(data)

18


'helloabci\nj\n\n12\n34'

#### tell : it gives cursor position

In [21]:
with open("text.txt") as f:
    data=f.read()
    print(f.tell()) # it gives cursor position

22


In [23]:
with open("text.txt") as f:
    data=f.read()
    f.seek(2)# From seek location
    print(f.read(10))

lloabci
j



#### create a mobile number contacts  file

In [24]:
file='contacts_data.txt'
def newcontact(name,contact):
    fh = open(file,'a')
    fh.write(name+" "+str(contact)+"\n")
    fh.close()
    return 'contact saved'

In [27]:
a , b = input().split()
newcontact(a,b)

a 123


'contact saved'

### Read a contact 

In [32]:
def readcontact(name):
    with open("contacts_data.txt",'r') as f:
        data_ = f.readlines()
        for string in data_:
            data_name, data_num = string.split()
            if name == data_name:
                return data_num
    
readcontact('b')

'324'

# Numpy
NumPy, short for Numerical Python, is one of the most important foundational packages for numerical computing in Python. 

NumPy operations perform complex computations on entire arrays without the need in Python for loops. 

NumPy arrays use much less memory than built-in Python sequences.

key features of NumPy is its N-dimensional array  object, or ndarray, which is a fast, flexible container for large datasets in Python.  

In [33]:
# Import the numpy library
# np is simply an alias, you may use any other alias, though np is quite standard
import numpy as np

In [36]:
# Creating a 1-D array using a list
# np.array() takes in a list or a tuple as argument, and converts into an array
li = [2, 4, 5, 6, 7, 9]
array_1d = np.array(li)
print(array_1d)
print(type(array_1d))
print(li)
print(type(li))

[2 4 5 6 7 9]
<class 'numpy.ndarray'>
[2, 4, 5, 6, 7, 9]
<class 'list'>


In [37]:
# Creating a 2-D array using two lists
array_2d = np.array([[2, 3, 4], [5, 8, 7]])
print(array_2d)

[[2 3 4]
 [5 8 7]]


In NumPy, dimensions are called axes. In the 2-d array above, there are two axes, having two and three elements respectively.

In NumPy terminology, for 2-D arrays:

axis = 0 refers to the rows
axis = 1 refers to the columns
![not](https://raw.githubusercontent.com/GirishaDevara/ML/master/MLND/2.NumPy/Introduction%20to%20NumPy/numpy_axes.jpg)

## Advantages of NumPy

- it is convenience and speed.
- You can write vectorised code on numpy arrays, not on lists. which is convenient to read and write.
- Numpy is much faster than the standard python ways to do computations.

Let's see an example of convenience, we'll see one later for speed.

Say you have two lists of numbers, and want to calculate the element-wise product. The standard python list way would need you to map a lambda function (or worse - write a for loop), whereas with NumPy, you simply multiply the arrays.

In [38]:
list_1 = [3, 6, 7, 5]
list_2 = [4, 5, 1, 7]

# the list way to do it: map a function to the two lists
product_list = list(map(lambda x, y: x*y, list_1, list_2))
print(product_list)

[12, 30, 7, 35]


In [40]:
# The numpy array way to do it: simply multiply the two arrays
array_1 = np.array(list_1)
array_2 = np.array(list_2)

array_3 = array_1*array_2
print(array_3)
print(type(array_3))

[12 30  7 35]
<class 'numpy.ndarray'>


Even simple mathematical operations on lists require for loops, unlike with arrays. For example, to calculate the square of every number in a list:

In [41]:
# Square a list
list_squared = [i**2 for i in list_1]

# Square a numpy array
array_squared = array_1**2

print(list_squared)
print(array_squared)

[9, 36, 49, 25]
[ 9 36 49 25]


#### Creating NumPy Arrays

In [42]:
# Convert lists or tuples to arrays using np.array()
# Note that np.array(2, 5, 6, 7) will throw an error - you need to pass a list or a tuple
array_from_list = np.array([2, 5, 6, 7]) 
array_from_tuple = np.array((4, 5, 8, 9))

print(array_from_list)
print(array_from_tuple)


[2 5 6 7]
[4 5 8 9]


#### The other common way is to initialise arrays.
The following ways are commonly used:

- np.ones(): Create array of 1s
- np.zeros(): Create array of 0s
- np.random.random(): Create array of random numbers
- np.arange(): Create array with increments of a fixed step size
- np.linspace(): Create array of fixed length

In [44]:
np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
# Tip: Use help to see the syntax when required
help(np.ones)

Help on function ones in module numpy:

ones(shape, dtype=None, order='C')
    Return a new array of given shape and type, filled with ones.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: C
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    
    Returns
    -------
    out : ndarray
        Array of ones with the given shape, dtype, and order.
    
    See Also
    --------
    ones_like : Return an array of ones with shape and type of input.
    empty : Return a new uninitialized array.
    zeros : Return a new array setting values to zero.
    full : Return a new array of given shape filled with value.
    
    
    Examples
    --------
   

In [46]:
# Creating a 5 x 3 array of ones
np.ones((5, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [47]:
# Notice that, by default, numpy creates data type = float64
# Can provide dtype explicitly using dtype
np.ones((5, 3), dtype = np.int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [48]:
# Creating array of zeros
np.zeros(4, dtype = np.int)

array([0, 0, 0, 0])

In [49]:
# Array of random numbers
np.random.random([3, 4])

array([[0.76515839, 0.94115304, 0.37616526, 0.92785942],
       [0.36754655, 0.95673919, 0.21381187, 0.13979473],
       [0.04194874, 0.62261923, 0.26029069, 0.79421848]])

In [50]:
# Creating a 4 x 3 array of 7s using np.full()
# The default data type here is int only
np.full((4,3), 7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [51]:
# Initialising a random 1000 x 300 array
rand_array = np.random.random((1000, 300))

# Print the second row
print(rand_array[1,:])

[2.14706052e-02 7.50683064e-02 1.31516498e-02 5.45846352e-01
 1.22227405e-01 4.36720588e-01 1.92632526e-01 5.55230367e-01
 9.72202330e-01 8.42624776e-01 3.29920180e-01 5.23749698e-01
 4.06675172e-01 8.82615298e-01 7.18659951e-02 5.06565100e-01
 3.80983560e-01 7.85995712e-01 5.83054074e-02 1.09006162e-01
 3.13528708e-01 7.88092662e-01 8.13843682e-02 3.18712588e-01
 9.01657403e-01 3.30982526e-01 5.32579912e-01 7.20982157e-02
 5.24487482e-01 1.99124748e-01 6.57727919e-01 9.61842693e-01
 6.67712126e-01 4.49409837e-01 3.34728452e-01 7.64757772e-01
 4.78785156e-01 9.66504887e-01 4.25509681e-01 5.75666905e-01
 5.13937001e-01 5.65363595e-01 2.87265080e-01 6.69307140e-01
 7.52186773e-01 2.84373409e-01 5.94145812e-01 1.10360088e-01
 4.44896702e-01 2.28298324e-01 7.96457232e-01 7.24648257e-01
 8.61122703e-01 4.89597671e-01 3.25724586e-01 1.80377188e-01
 5.76720324e-01 3.03919175e-01 1.70469997e-01 7.05556930e-01
 6.51569781e-01 6.38887628e-01 2.71809721e-01 8.94692010e-01
 8.40894232e-01 8.245448

In [52]:
# Inspecting shape, dtype, ndim and itemsize
print("Shape: {}".format(rand_array.shape))
print("dtype: {}".format(rand_array.dtype))
print("Dimensions: {}".format(rand_array.ndim))
print("Item size: {}".format(rand_array.itemsize))

Shape: (1000, 300)
dtype: float64
Dimensions: 2
Item size: 8


Reading 3-D arrays is not very obvious, because we can only print maximum two dimensions on paper, and thus they are printed according to a specific convention. Printing higher dimensional arrays follows the following conventions:

- The last axis is printed from left to right
- The second-to-last axis is printed from top to bottom
- The other axes are also printed top-to-bottom, with each slice separated by another using an empty line

Let's see some examples.

In [53]:
# Creating a 3-D array
# reshape() simply reshapes a 1-D array 
array_3d = np.arange(24)
print(array_3d)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [54]:
array_3d.reshape(2, 3, 4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

- The last axis has 4 elements, and is printed from left to right.
- The second last has 3, and is printed top to bottom
- The other axis has 2, and is printed in the two separated blocks

#### Subset, Slice, Index and Iterate through Arrays
For one-dimensional arrays, indexing, slicing etc. is similar to python lists - indexing starts at 0.

In [55]:
# Indexing and slicing one dimensional arrays
array_1d = np.arange(10)
print(array_1d)

[0 1 2 3 4 5 6 7 8 9]


In [56]:
# Third element
print(array_1d[2])

# Specific elements
# Notice that array[2, 5, 6] will throw an error, you need to provide the indices as a list
print(array_1d[[2, 5, 6]])

# Slice third element onwards
print(array_1d[2:])

# Slice first three elements
print(array_1d[:3])

# Slice third to seventh elements
print(array_1d[2:7])

# Subset starting 0 at increment of 2 
print(array_1d[0::2])


2
[2 5 6]
[2 3 4 5 6 7 8 9]
[0 1 2]
[2 3 4 5 6]
[0 2 4 6 8]


#  Pandas
Pandas is a library built using NumPy specifically for data analysis. You'll be using Pandas heavily for data manipulation, visualisation, building machine learning models, etc.

There are two main data structures in Pandas - Series and Dataframes. The default way to store data is dataframes, and thus manipulating dataframes quickly is probably the most important skill set for data analysis.

1. The pandas Series (similar to a numpy array)
    - Creating a pandas series
    - Indexing series
2. Dataframes
    - Creating dataframes from dictionaries
    - Importing CSV data files as pandas dataframes
    - Reading and summarising dataframes
    - Sorting dataframes


## 1. The Pandas Series
A series is similar to a 1-D numpy array, and contains scalar values of the same type (numeric, character, datetime etc.). A dataframe is simply a table where each column is a pandas series.

In [57]:
# import pandas, pd is an alias
import pandas as pd
import numpy as np

# Creating a numeric pandas series
s = pd.Series([2, 4, 5, 6, 9])
print(s)
print(type(s))

0    2
1    4
2    5
3    6
4    9
dtype: int64
<class 'pandas.core.series.Series'>


In [58]:
# creating a series of characters
# notice that the 'dtype' here is 'object'
char_series = pd.Series(['a', 'b', 'af'])
char_series

0     a
1     b
2    af
dtype: object

In [59]:
# creating a series of type datetime
date_series = pd.date_range(start = '11-09-2017', end = '12-12-2017')
date_series

DatetimeIndex(['2017-11-09', '2017-11-10', '2017-11-11', '2017-11-12',
               '2017-11-13', '2017-11-14', '2017-11-15', '2017-11-16',
               '2017-11-17', '2017-11-18', '2017-11-19', '2017-11-20',
               '2017-11-21', '2017-11-22', '2017-11-23', '2017-11-24',
               '2017-11-25', '2017-11-26', '2017-11-27', '2017-11-28',
               '2017-11-29', '2017-11-30', '2017-12-01', '2017-12-02',
               '2017-12-03', '2017-12-04', '2017-12-05', '2017-12-06',
               '2017-12-07', '2017-12-08', '2017-12-09', '2017-12-10',
               '2017-12-11', '2017-12-12'],
              dtype='datetime64[ns]', freq='D')

## Indexing Series
Indexing series is exactly same as 1-D numpy arrays - index starts at 0.

In [60]:
# Indexing pandas series: Same as indexing 1-d numpy arrays or lists
# accessing the fourth element
s[3]

6

In [62]:
# accessing elements starting index = 2 till the end
s[2:]

2    5
3    6
4    9
dtype: int64

In [61]:
# accessing the second and the fourth elements
# note that s[1, 3] will not work, you need to pass the indices [1, 3] as a list inside the original []
s[[1, 3]]

1    4
3    6
dtype: int64

### The Pandas Dataframe
Dataframe is the most widely used data-structure in data analysis. It is a table with rows and columns, with rows having an index and columns having meaningful names.
#### Creating dataframes from dictionaries
There are various ways of creating dataframes, such as creating them from dictionaries, JSON objects, reading from txt, CSV files, etc.

In [63]:
# keys become column names
df = pd.DataFrame({'name': ['Vinay', 'Kushal', 'Aman', 'Saif'], 
                   'age': [22, 25, 24, 28], 
                    'occupation': ['engineer', 'doctor', 'data analyst', 
                                   'teacher']})
df


name  age    occupation
0   Vinay   22      engineer
1  Kushal   25        doctor
2    Aman   24  data analyst
3    Saif   28       teacher

### Importing CSV data files as pandas dataframes

In [64]:
# reading a CSV file as a dataframe
titanic_df = pd.read_csv("titanic.csv")

In [65]:
titanic_df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
5              6         0       3   
6              7         0       1   
7              8         0       3   
8              9         1       3   
9             10         1       2   
10            11         1       3   
11            12         1       1   
12            13         0       3   
13            14         0       3   
14            15         0       3   
15            16         1       2   
16            17         0       3   
17            18         1       2   
18            19         0       3   
19            20         1       3   
20            21         0       2   
21            22         1       2   
22            23         1       3   
23            24         1       1   
24            25         0       3   
25            26         1       3   
26            27         0       3   
27            28         0       1   
28            29         1       3   
29            30         0       3   
..           ...       ...     ...   
861          862         0       2   
862          863         1       1   
863          864         0       3   
864          865         0       2   
865          866         1       2   
866          867         1       2   
867          868         0       1   
868          869         0       3   
869          870         1       3   
870          871         0       3   
871          872         1       1   
872          873         0       1   
873          874         0       3   
874          875         1       2   
875          876         1       3   
876          877         0       3   
877          878         0       3   
878          879         0       3   
879          880         1       1   
880          881         1       2   
881          882         0       3   
882          883         0       3   
883          884         0       2   
884          885         0       3   
885          886         0       3   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name  Gender   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
5                                     Moran, Mr. James    male   NaN      0   
6                              McCarthy, Mr. Timothy J    male  54.0      0   
7                       Palsson, Master. Gosta Leonard    male   2.0      3   
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                  Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   
10                     Sandstrom, Miss. Marguerite Rut  female   4.0      1   
11                            Bonnell, Miss. Elizabeth  female  58.0      0   
12                      Saundercock, Mr. William Henry    male  20.0      0   
13                         Andersson, Mr. Anders Johan    male  39.0      1   
14                Vestrom, Miss. Hulda Amanda Adolfina  female  14.0      0   
15                    Hewlett, Mrs. (Mary D Kingcome)   female  55.0      0   
16                                Rice, Master. Eugene    male   2.0      4   
17                        Williams, Mr. Charles Eugene    male   NaN      0   
18   Vander Planke, Mrs. Julius (Emelia Maria Vande...  female  31.0      1   
19                             Masselmani, Mrs. Fatima  female   NaN

#### Reading and Summarising Dataframes
After you import a dataframe, you'd want to quickly understand its structure, shape, meanings of rows and columns etc. Further, you may want to look at summary statistics - such as mean, percentiles etc.

In [66]:
# Looking at the top and bottom entries of dataframes
titanic_df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name  Gender   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [68]:
titanic_df.tail()

PassengerId  Survived  Pclass                                      Name  \
886          887         0       2                     Montvila, Rev. Juozas   
887          888         1       1              Graham, Miss. Margaret Edith   
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   
889          890         1       1                     Behr, Mr. Karl Howell   
890          891         0       3                       Dooley, Mr. Patrick   

     Gender   Age  SibSp  Parch      Ticket   Fare Cabin Embarked  
886    male  27.0      0      0      211536  13.00   NaN        S  
887  female  19.0      0      0      112053  30.00   B42        S  
888  female   NaN      1      2  W./C. 6607  23.45   NaN        S  
889    male  26.0      0      0      111369  30.00  C148        C  
890    male  32.0      0      0      370376   7.75   NaN        Q

In [70]:
# Looking at the datatypes of each column
titanic_df.info()

# Note that each column is basically a pandas Series of length 8399
# The ID columns are 'objects', i.e. they are being read as characters
# The rest are numeric (floats or int)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
PassengerId    891 non-null int64
Survived       891 non-null int64
Pclass         891 non-null int64
Name           891 non-null object
Gender         891 non-null object
Age            714 non-null float64
SibSp          891 non-null int64
Parch          891 non-null int64
Ticket         891 non-null object
Fare           891 non-null float64
Cabin          204 non-null object
Embarked       889 non-null object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.6+ KB


In [71]:
# Describe gives you a summary of all the numeric columns in the dataset
titanic_df.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [73]:
# The number of rows and columns
titanic_df.shape

(891, 12)

###  Problem 
Given a series of integer pairs A and B, output the sum of A and B. 

- Input Format:

Each line contains two integers, A and B. One input file may contain several pairs P.

- Output Format:

Output a single integer per line - The sum of A and B.

| Sample Input   |      Sample Output      |
|----------|:-------------:|
| 1  2 |  3 |
| 2  5 |   7   |
| 10  14 | 24 |

In [74]:
while True:
    a,b = map(int,input().split())
    print(a+b)
    if a == " ":
        break

1 2
3
2 3
5



ValueError: not enough values to unpack (expected 2, got 0)

# Exception Handling
 
 Exception Errors :

- ZeroDivisionError
- IOError : if file can’t be opened
- KeyboardInterrupt : when an unrequired key is pressed by the user
- ValueError : when built-in function receives a wrong argument
- EOFError : if End-Of-File is hit without reading any data
- ImportError : if it is unable to find the module


try:

The code with the exception that you want to catch. If an exception is raised, control flow leaves this block immediately and goes to the except block

except [(Exception[, Exception])] [as VAR]:


In [71]:
10/0

ZeroDivisionError: division by zero

In [74]:
def divide(x,y):
    return x//y
x = int(input())
y = int(input())
divide(x,y)

21
0


ZeroDivisionError: integer division or modulo by zero

In [75]:
def divide(x,y):
    try:
        return x//y
    except ZeroDivisionError:
        return "your dividing by 0 "
    
x = int(input())
y = int(input())
divide(x,y)

21
0


'hey you are dividing by 0 '

[Problem 2](https://www.hackerearth.com/practice/basic-programming/bit-manipulation/basics-of-bit-manipulation/practice-problems/algorithm/mystery-30/)

In [79]:
def foo10():
    try:
        1 + '0'
    except:
        print('caught exception')
    else:  #  runs only when there is no excption 
        print('no exception raised')
    finally:
        print('finally')

In [80]:
foo10()

caught exception
finally
